[package]
name = "Liveweek2"
version = "0.1.0"
edition = "2021"

[dependencies]

[workspace]
members = [
    "FirstThread",
    "DivideWork",
    "thread_builder",
    "scoped_threads",
    "atomic_counter",
    "atomic_counter_timed",
    "mutexes",
    "read_write"
]